### ISSUE TITLE
Icon Change Issue

### ISSUE THREAD

**Issue by FvApp** [skb1129/react-native-change-icon#16]
Icon not changed in Recent task in IPHONE & IPAD. Please help us.

**Comment by skb1129** [comment]
@FvApp, I tried it and it is working on the simulator and my device running iOS 13.4.1.
Please share more details so that I can check this issue:
1. Which React-Native version are you using?
2. Which device are you using and what is the iOS version it's running?
3. Apart from the icon in the recent tasks, does the icon change work without any problems?

**Comment by FvApp** [comment]
Please let me know the solution for my problem

**Comment by FvApp** [comment]
"react-native": "0.62.2",
"react-native-change-icon": "^2.0.3",

**Comment by FvApp** [comment]
Apart from the icon in the recent tasks, icon changes work without any problems.

**Comment by skb1129** [comment]
@FvApp Which device are you using and what is the iOS version it's running?

**Comment by FvApp** [comment]
IPAD  13.4.1

**Comment by skb1129** [comment]
@FvApp I have tried the same in a simulator on iPad, iPad Air, and iPad Prod. It seems to be working just fine on all these simulators, the icon gets changes in all the places that it should. I don't have any real iPad device that I can test it on.

As far as this package is concerned, for iOS, I am using [this method](https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname) provided by the Apple UIKit library and if this issue does exist, it should be an issue for the Apple UIKit library and not this package.

Closing this issue now.
