### ISSUE TITLE
Change Icon success, but MainActivity class does not exist error

### ISSUE THREAD

**Issue by niraj-rahi-smartdata** [skb1129/react-native-change-icon#29]
```
<activity-alias
            android:name="com.truecharger.MainActivitylos"
            android:enabled="true"
            android:icon="@mipmap/los"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>
```

Let me know what is wrong

**Comment by skb1129** [comment]
@niraj-rahi-smartdata Please use the bug report issue template that is provided to you while creating the issue, that will help me clearly identify the problem.
If this is not a bug and you are just facing some setup problem, I suggest you thoroughly go through the README and try the example project that is given in this repository. If your issue is still not resolved, you may communicate over this [discussions](https://github.com/skb1129/react-native-change-icon/discussions/31) channel, I will surely help
