### ISSUE TITLE
[FEATURE] Disable alert after changing the icon

### ISSUE THREAD

**Issue by rusakovic** [skb1129/react-native-change-icon#32]
**Platform**
 - [ x ] iOS

**Description**

**To Reproduce**
1. Icon is changed via `changeIcon('iconname')`
2. Alert is shown

**Expected behavior**
Don't show alert

**Screenshots**
![image](https://user-images.githubusercontent.com/17801144/110110820-6fee1980-7dc0-11eb-9f79-fc36d6c4c265.png)

**Device (please complete the following information):**
 - Device: [ iPhone 8 Plus]
 - OS: [iOS 13.3]

**Versions**
 - react-native: [e.g. 0.62.3]
 - react-native-change-icon: [3.0.0]

**Comment by skb1129** [comment]
@rusakovic This change is not technically viable due to restrictions by iOS itself. Please note that this alert has not been added by me. The alert is not generated by the application, it is actually generated by the iOS system to notify the user that the icon for the app currently in use has changed. There is no other way around this. Please refer to the following official Apple documentation for more details:
https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/
https://developer.apple.com/app-store/review/guidelines/#alternate-app-icons

**Comment by oleksandrParniekov** [comment]
@skb1129 Thank you for the explanation. Maybe you can add this to Readme :)
